# Generated by Django 3.1.6 on 2021-04-02 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platform',
            name='category',
            field=models.CharField(choices=[('UP', 'Upcoming Project'), ('AT', 'Active Project'), ('ED', 'Ended Project')], max_length=3),
        ),
    ]
