# Generated by Django 3.1.6 on 2021-04-06 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0002_auto_20210402_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='category',
        ),
    ]
